### ISSUE TITLE
Can't find to load in CloudPebble

### ISSUE THREAD

**Issue by hitormiss** [smallstoneapps/utils#2]
Since you've moved/renamed this from **pebble-assist** to **utils**, I can't "find" this package using the search box on the DEPENDENCIES tab on CloudPebble to add to my Project (because the name is too short / too common).  Same for your other packages.  Maybe you can rename it to **smallstoneapps-utils**? (or **pebble-utils**)

**Comment by matthewtole** [comment]
Hi @hitormiss,

It looks like CloudPebble doesn't handle searching for scoped packages. I will file a bug with them to get that fixed.

In the meantime, you can just enter the package name manually into the dependencies field. 

![screen shot 2016-07-01 at 11 12 52](https://cloud.githubusercontent.com/assets/1440396/16530398/c7ea8420-3f7c-11e6-9fce-753b6eaefd26.png)
